### ISSUE TITLE
Web Developer | Front-End

### ISSUE THREAD

**Issue by Lucas-Henrique-Lopes-Costa** [Lucas-Henrique-Lopes-Costa/Lucas-Henrique-Lopes-Costa#1]
## Required for any path
- [x] Git - Version Control
- [x] Basic Terminal Usage
- [x] Data Structures & Algorithms
- [x] GitHub
- [ ] Licenses
- [ ] Semantic Versioning
- [ ] SSH
- [ ] HTTP/HTTPS and APIs
- [ ] Design Patterns
- [ ] Character Encodings

# Front-end
## Internet
- [ ] How does the internet work?
- [ ] What is HTTP?
- [ ] Browsers and how they work?
- [ ] DNS and how it works?
- [ ] What is Domain Name?
- [ ] What is hosting?

## HTML
- [x] Learn the basics
- [x] Writing Semantic HTML
- [x] Forms and Validations
- [ ] Conventions and Best Practices
- [ ] Accessibility
- [ ] SEO Basics

## CSS
- [x] Learn the basics
- [ ] Making Layouts
  - [ ] Floats
  - [ ] Positioning
  - [ ] Display
  - [x] Box Model
  - [x] CSS Grid
  - [x] Flex Box
- [x] Responsive design and Media Queries

## JavaScript
- [x] Syntax and Basic Constructs
- [x] Learn DOM Manipulation
- [ ] Learn Fetch API / Ajax (XHR)
- [ ] ES6+ and modular JavaScript
- [ ] Understand the concepts Hoisting, Event Bubbling, Scope, Prototype, Shadow DOM, strict

## Version Control Systems
- [x] Basic Usage of Git
- [x] Create account and Learn to use GitHub

## Web Security Knowledge
- [ ] Get at least a basic knowledge of all of these
  - [ ] HTTPS
  - [ ] Content Security Policy
  - [ ] CORS
  - [ ] OWASP Security Risks

## Package Managers
- [x] npm and yarn both are fine, pick one or learn both, there is not much difference.

## CSS Architecture
- [ ] With modern frameworks and CSS-in-JS you don't have to worry about these anymore but still it would be a good idea to get familiarized with **BEM** atleast.
- [ ] BEM

## CSS Preprocessors
- [ ] With how the modern frameworks there has been more push towards CSS-in-JS so you may not need these but still a good idea to familiarize yourself.
- [ ] Sass
- [ ] PostCSS

### Task Runners
  - [ ] npm scripts
### Linters and Formatters
  - [x] Prettier
  - [x] ESLint
### Module Bundlers
  - [ ] Webpack

## Pick a Framework
- [ ] React.js
  - [ ] Redux
  - [ ] MobX

## Modern CSS
- [ ] Styled Component
- [ ] CSS Module

## Web Components
- [ ] HTML Templates
- [ ] Custom Elements
- [ ] Shadow DOM

## CSS Frameworks
- [ ] Reactstrap
- [ ] Material UI
- [ ] Bootstrap

## Testing your Apps
- [ ] Learn the difference between **Unit**, **Integration**, and **Functional** tests and learn how to write them with the tools listed on the left.
- [ ] Jest
- [ ] react-testing-library
- [ ] Cypress
- [ ] Enzyme

## Type Checkers
- [ ] TypeScript

## Progressive Web Apps
- [ ] Storage
- [ ] Web Sockets
- [ ] Service Workers
- [ ] Location
- [ ] Notifications
- [ ] Device Orientation
- [ ] Payments
- [ ] Credentials
- [ ] Learn different Web APIs used in PWAS

- [ ] PRPL Pattern
- [ ] RAIL Model
- [ ] Using Lighthouse
- [ ] Using Dev Tools
- [ ] Calculating, Measuring and improving performance

## Server Side Rendering (SSR)
- [ ] React.js
  - [ ] Next.js

## GraphQL
- [ ] Apollo

## Static Site Generators
- [ ] Next.js
- [ ] Gatsby JS

## Mobile Applications
- [ ] React Native
- [ ] Flutter

## Desktop Applications
- [ ] Electron

## Web Assembly
- [ ] Web Assembly or WASM is the binary instructions generated from higher level languages such as **Go, C, C++ or Rust.** It is faster than JavaScript and WASM 1.0 has already shipped in the major browsers W3C accepted it as an official standard at the end of 2019. It will still take quite some time to go mainstream though.
  * Resumindo será uma espécie de máquina virtual para acessar qualquer linguagem pela Web.
